### ISSUE TITLE
tf.SequenceExample support

### ISSUE THREAD

**Issue by b3nk4n** [tensorflow/transform#16] opened 2017-05-30 11:52 UTC
After a short look into the code of `tensorflow_transform.coders.ExampleProtoCoder`, it looks like tf.SequenceExample record files are not supported yet. Is this already on the list, or did I miss something and this es already supported by tf.Transform?

Thank you in advance!

**Comment by KesterTong** [comment] 2017-07-27 14:54
tf.SequenceExample is not supported but we are aiming to do it this quarter (i.e. by end of September)

**Comment by gdj0nes** [comment] 2018-05-24 16:56
Is there a status update on this?

**Comment by KesterTong** [comment] 2018-05-24 16:59
We are still working on SequenceExample support, will update this bug with updates.

**Comment by KesterTong** [comment] 2018-10-28 01:13
No we are still working towards SequenceExample support

**Comment by martin-laurent** [comment] 2018-12-13 22:46
Is there an update on `SequenceExample` support?

**Comment by skiler07** [comment] 2019-01-25 12:38
Its 2019, already, is `SequenceExample` alive? Currently, I'm using `VarLenFeature` to write tf records as a work around, which doesn't work in serving.

**Comment by hgadig** [comment] 2019-03-26 17:02
Team is still working towards SequenceExample support and will keep you posted here once it is ready.

**Comment by htahir1** [comment] 2019-08-22 15:58
@skiler07 in the meanwhile could you kindly also perhaps briefly discuss how you solved the problem using VarLenFeature. Its a bit of a head scratcher for me. 

Im trying  to make a TFX pipeline work with sliding windows (i.e.)

0 1 2 3 4
1 2 3 4 5
2 3 4 5 6

To feed into a LSTM model. But I see now way of doing this with TF.Transform

**Comment by nuwansam** [comment] 2020-11-01 05:38
While probably a bit hacky of a solution, one alternative could be to flatten the features within the beam pipeline prior to calling the transform, and in the preprocess_fn only transform a single time step per each feature and then use the stats gathered in the transformation to transform the other timesteps of each feature, and then take the transformed result and unflatten the example back to a sequence example.

**Comment by tanguycdls** [comment] 2021-06-08 07:20
Hello, since TFX-BSL did the dev on reading sequence example to pa.record batches it seems to now work for the fit part. see https://github.com/tensorflow/tfx-bsl/blob/925bf2bcbf536c2fd5af62e16c141ad2ce7622e2/tfx_bsl/tfxio/tf_sequence_example_record.py every sequence item is put in a ragged tensor in 3D that we can then convert to sparse using .to_sparse() in the preprocessing function.

However writing back the sequence example is not supported because the only encoder available is recordbatches to example and not record batches to sequence example and it breaks because the tensor representation in ragged is not supported while writing.

Is there still a plan to make that feature available ? thanks

**Comment by gaikwadrahul8** [comment] 2022-12-15 16:46
Hi, @b3nk4n 

Apologies for the delay and we have updated our official documentation w.r.t `tf.train.SequenceExample()` [here](https://www.tensorflow.org/api_docs/python/tf/train/SequenceExample) and since version 1.10.0 TFX Transform supports `SequenceExamples` natively which is confirmed by @iindyk in this [comment](https://github.com/tensorflow/tfx/issues/4714#issuecomment-1351368450) 

Could you please confirm if this issue is resolved for you ?Please feel free to close the issue if it is resolved ? 

Thank you!

**Comment by gaikwadrahul8** [comment] 2023-01-15 18:37
Hi, @b3nk4n 

One of our user @AlexanderLavelle has added complete approach how to use `tf.SequenceExample `records which is depending on the payload format in TFX transform component [here](https://github.com/tensorflow/tfx/issues/5520#issuecomment-1382719616) you can refer that comment

Closing this issue due to lack of recent activity for couple of weeks. Please feel free to reopen the issue or post comments, if you need any further assistance or update. Thank you!

**Closed** 2023-01-15 18:37 UTC
Labels: stat:awaiting response, type:feature

**Comment by AlexanderLavelle** [comment] 2023-01-27 19:58
@gaikwadrahul8 If you use ImportExampleGen, my solution works; unfortunately, if you use FileBasedExampleGen, the trainer looks for `payload_format` but FBEG accepts `output_data_format`
