### ISSUE TITLE
Create a coder for ExampleListWithContext

### ISSUE THREAD

**Issue by tillwf** [tensorflow/transform#163] opened 2020-02-20 12:06 UTC
In order to use tfranking with the format ELWC, is it possible to create a `ELWCProtoCoder` which would inherit `ExampleProtoCoder`. It could be use with beam to create appropriate tfrecords.

**Comment by rmothukuru** [comment] 2020-02-24 05:30
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow Transform version. 

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new.choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by tillwf** [comment] 2020-02-25 09:22
I'm using Ubuntu 19.10 with these package versions:

```
tensorflow==2.1.0
tensorflow-estimator==2.1.0
tensorflow-metadata==0.15.1
tensorflow-ranking==0.2.2
tensorflow-serving-api==2.1.0
tensorflow-transform==0.15.0
```

I want to use this script: https://github.com/tensorflow/ranking/blob/master/tensorflow_ranking/examples/tf_ranking_tfrecord.py

Previously I was using Beam WriteToTfRecord like so:

```python
    coder = tft.coders.ExampleProtoCoder(metadata.schema)

    return (data
            | 'WriteData to {location}'.format(
                location=location) >> beam.io.WriteToTFRecord(
                file_path_prefix=location,
                coder=coder,
                file_name_suffix=".tfrecords"
            ))
```
and with these tfrecords I was apply my algorithm.

To use `tf-ranking` I have to transform my data to `ExampleListWithContext` which is coherent with the data I have but I'm not sure where to do it. 

My question is: would it be possible to create a specific Proto Coder for the format ELWC ?

I did something like this (which works in my use case) but I'm not sure it is correct (I skipped the decode part):

```python
class ELWCProtoCoder(object):

    def __init__(self, context_schema, examples_schema, n_examples, serialized=True):
        self._context_schema = context_schema
        self._examples_schema = examples_schema
        self._n_examples = n_examples
        self._serialized = serialized

        self._encode_example_cache = input_pb2.ExampleListWithContext()
        self._decode_example_cache = input_pb2.ExampleListWithContext()

        self._context = ExampleProtoCoder(self._context_schema, serialized=False)

        self._examples = [
            ExampleProtoCoder(self._examples_schema, serialized=False)
            for i in range(n_examples + 1)
        ]

    def __reduce__(self):
        return ELWCProtoCoder, (
            self._context_schema,
            self._examples_schema,
            self._n_examples,
            self._serialized
        )

    def encode(self, instance):

        encoded_context = self._context.encode(
            {
                feat.name: instance[feat.name]
                for feat in self._context_schema.feature
            }
        )

        encoded_examples = []
        for i in range(self._n_examples + 1):
            tmp_instance = {
                feat.name: instance[feat.name][i]
                for feat in self._examples_schema.feature
            }
            encoded_examples.append(self._examples[i].encode(tmp_instance))

        elwc = input_pb2.ExampleListWithContext(
            context=encoded_context,
            examples=encoded_examples
        )

        if self._serialized:
            return elwc.SerializeToString()
        else:
            return elwc
```

**Comment by zoyahav** [comment] 2020-04-14 14:46
If that works for your use case then this is fine.

**Comment by wed0itagain** [comment] 2020-06-06 15:14
When running this i get the error

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-35-b1be0162f9de> in <module>()
     54         else:
     55             return elwc
---> 56 ELWCProtoCoder(schema_gen.outputs['schema'],example_gen.outputs['examples'],3)

2 frames
/usr/local/lib/python3.6/dist-packages/tensorflow_transform/tf_metadata/schema_utils.py in schema_as_feature_spec(schema_proto)
    189     ValueError: If the schema proto is invalid.
    190   """
--> 191   for feature in schema_proto.feature:
    192     if RAGGED_TENSOR_TAG in feature.annotation.tag:
    193       raise ValueError(

AttributeError: 'Channel' object has no attribute 'feature'
```

Whats "feature" referring to?

**Comment by tillwf** [comment] 2020-06-07 08:53
This errors comes from `schema_utils.py` because `ExampleProtoCoder` is calling `schema_as_feature_spec` with a schema as parameter.

In your example, the schema that fails is either `schema_gen.outputs['schema']` or `example_gen.outputs['examples']`. Do you have the specific line in the `ELWCProtoCoder` that fails ?

**Comment by wed0itagain** [comment] 2020-06-07 10:26
Hi, 

To test this i also used: 
```
ELWCProtoCoder(schema_gen.outputs['schema'],schema_gen.outputs['schema'],3)
```
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-64-a905bc5d66e5> in <module>()
----> 1 ELWCProtoCoder(schema_gen.outputs['schema'],schema_gen.outputs['schema'],3)

2 frames
<ipython-input-63-0eea437f5db0> in __init__(self, context_schema, examples_schema, n_examples, serialized)
     15         self._decode_example_cache = input_pb2.ExampleListWithContext()
     16 
---> 17         self._context = tensorflow_transform.coders.ExampleProtoCoder(self._context_schema, serialized=False)
     18 
     19         self._examples = [

/usr/local/lib/python3.6/dist-packages/tensorflow_transform/coders/example_proto_coder.py in __init__(self, schema, serialized)
    280     self._feature_handlers = []
    281     for name, feature_spec in six.iteritems(
--> 282         schema_utils.schema_as_feature_spec(schema).feature_spec):
    283       if isinstance(feature_spec, tf.io.FixedLenFeature):
    284         self._feature_handlers.append(

/usr/local/lib/python3.6/dist-packages/tensorflow_transform/tf_metadata/schema_utils.py in schema_as_feature_spec(schema_proto)
    189     ValueError: If the schema proto is invalid.
    190   """
--> 191   for feature in schema_proto.feature:
    192     if RAGGED_TENSOR_TAG in feature.annotation.tag:
    193       raise ValueError(

AttributeError: 'Channel' object has no attribute 'feature'
```

For my understanding: The ELWCProtoCoder needs 2 Schemas Protos, which are a wrapper around the corresponding context or example feature. I used the Outputs i got from my SchemaGen(...). Am i right? 


```
feat.name: instance[feat.name]
                for feat in self._context_schema.feature
```

**Comment by tillwf** [comment] 2020-06-10 09:29
The type of schemas should be `tensorflow_metadata.proto.v0.schema_pb2.Schema` which comes from:

```python
from tensorflow_transform.tf_metadata import dataset_metadata, schema_utils
context_schema = dataset_metadata.DatasetMetadata(
        schema_utils.schema_from_feature_spec(schema)
 ).schema
```
`schema` inside `schema_from_feature_spec` is a dict which looks like this:

```python
{
    "feature_name": tf.io.FixedLenFeature(shape=[], dtype=tf.int64),
}
```

**Comment by wed0itagain** [comment] 2020-06-18 08:59
Okay thank you. That helped alot. 

What type is "instance" in the encode function or where does it come from?

**Comment by tillwf** [comment] 2020-06-18 10:58
`instance` is a `dict` of the data you load (`{feature_name: feature_value}`). Here is the encode method of ExampleProtoCoder that could help you understand:

https://github.com/tensorflow/transform/blob/v0.22.0/tensorflow_transform/coders/example_proto_coder.py#L311-L327

**Comment by wed0itagain** [comment] 2020-06-24 12:15
I've found a few options but i'm unsure which one to follow: 

1.
```
 tft.TFTransformOutput("transform_uri").transform_raw_features("raw_features") 
```

which gives a dict whose keys are feature names and values.

2.
```
 import tensorflow as tf

def _bytes_feature(value):
    return tf.train.Feature(bytes_list=tf.train.BytesList(value=[value]))

def _float_feature(value):
    return tf.train.Feature(float_list=tf.train.FloatList(value=[value]))

def _int64_feature(value):
    return tf.train.Feature(int64_list=tf.train.Int64List(value=[value]))

INSTANCE_dict = {}
INSTANCE_dict["feature"] = _int64_feature("List of Feature Values") 

```

Both seem like a viable option but is there any better one?

**Comment by wed0itagain** [comment] 2020-07-01 14:55
After trying multiple times i finally got it almost. 

The problem is this line of code: 
```
        for i in range(self._n_examples + 1):
            tmp_instance = {
                feat.name: instance[feat.name][i] # <------
                for feat in self._examples_schema.feature
            }

```
Without the [i] index i don't get the "TypeError: **'float' object is not subscriptable**" error. So i guess that's the problem. How did you get around that errror? 

Thanks for helping

**Comment by tillwf** [comment] 2020-07-01 18:20
I think context features are single values and examples values are lists of values. That is why the value in `instance[feat.name]` for the examples features are list and can be iterated. Maybe my code is too related to my data.

**Comment by wed0itagain** [comment] 2020-07-24 20:05
Finally i have found some time and i have good news... it's working for my case! 

Thank you for helping me in the toughest times ;) 

For future reference:  

I have two TfRecordDataset...

```
iterator=iter(dataset)`
iterator_context=iter(dataset2)
encoded_examples=[]


with tf.io.TFRecordWriter('your_data.tfrecords') as writer:


   for length in tensor: 

```
> tensor =  1-D Tensor with same values as the anticipated count of examples in one ELWC

```    
     for i in range(length):
        

        example_str = iterator.get_next().numpy()
        tft_decoded=tft.coders.ExampleProtoCoder(feature_tft).decode(example_str)
        
        tmp_instance = {
                feat.name: tft_decoded[feat.name]
                for feat in example_schema.feature
              }
        
        encoded_examples.append(tft.coders.ExampleProtoCoder(example_schema, serialized=False).encode(tmp_instance))

        
    for count, item in enumerate(encoded_examples):
                    
      if (count+1) == length.numpy(): 
         
         example_str = iterator_context.get_next().numpy()
         example_proto = tf.train.Example.FromString(example_str)
        
         ELWC = input_pb2.ExampleListWithContext(context=example_proto, examples=encoded_examples)
         encoded_examples.clear()
         writer.write(ELWC.SerializeToString())


```

**Comment by arghyaganguly** [comment] 2021-04-27 10:54
Closing this based on the above comment trace.Thanks.

**Closed by arghyaganguly** 2021-04-27 10:54 UTC
Labels: stat:awaiting tensorflower, type:feature
