### ISSUE TITLE
Error using apply_function

### ISSUE THREAD

**Issue by fabito** [tensorflow/transform#54] opened 2018-05-03 01:36 UTC
Hi,

I'm trying to apply the function below:

```python
def _group_ethnic(original):
    unknonw_cat = tf.constant(['UNCODABLE', 'UNCODED', 'ASIAN AMERICAN 2', 'NULL'])
    caucasian_cat = tf.constant(['SCANDINAVIAN', 'MEDITERRANEAN', 'WESTERN EUROPEAN'])
    east_asian_cat = tf.constant(['POLYNESIAN', 'EAST ASIAN'])
    zero = tf.constant(0, dtype=tf.int64)
    return tf.case({
        tf.greater(tf.count_nonzero(tf.equal(unknonw_cat, original)), zero): lambda: tf.constant('Unknown'),
        tf.greater(tf.count_nonzero(tf.equal(caucasian_cat, original)), zero): lambda: tf.constant('CAUCASIAN (NON-HISPANIC)'),
        tf.greater(tf.count_nonzero(tf.equal(east_asian_cat, original)), zero): lambda: tf.constant('EAST ASIAN/PACIFIC ISLANDER')
    }, default=lambda: original, exclusive=True, name='group_ethnic')
```
using `tft.apply_function` like this:

```python
new_ethnic_group = tft.apply_function(_group_ethnic, inputs['ethnic'])
outputs['ethnic'] = tft.string_to_int(new_ethnic_group, vocab_filename='ethnic')
```
You can also see it running on [colab](https://colab.research.google.com/drive/1JInWjkPVQ7jTg92HF7BSEj9aDAnnQgGH).

But the following error is being raised:

```
File "/home/user/.virtualenvs/env1/local/lib/python2.7/site-packages/tensorflow_transform/beam/impl.py", line 670, in expand
  outputs = self._preprocessing_fn(impl_helper.copy_tensors(inputs))
File "/home/user/Workspaces/env1/proj/preprocess/transform.py", line 153, in preprocessing_fn
  new_ethnic_group = tft.apply_function(_group_ethnic, inputs['ethnic'])
File "/home/user/.virtualenvs/env1/local/lib/python2.7/site-packages/tensorflow_transform/api.py", line 161, in apply_function
  return FunctionApplication(fn, args).user_output
File "/home/user/.virtualenvs/env1/local/lib/python2.7/site-packages/tensorflow_transform/api.py", line 89, in __init__
  output = fn(*args)
File "/home/user/Workspaces/env1/proj/preprocess/transform.py", line 148, in _group_ethnic
  tf.greater(tf.count_nonzero(tf.equal(unknown_cat, original)), zero): lambda: tf.constant('Unknown'),
File "/home/user/.virtualenvs/env1/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_math_ops.py", line 1489, in equal
  "Equal", x=x, y=y, name=name)
File "/home/user/.virtualenvs/env1/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 519, in _apply_op_helper
  repr(values), type(values).__name__))
TypeError: Expected string passed to parameter 'y' of op 'Equal', got <tensorflow.python.framework.sparse_tensor.SparseTensor object at 0x7fbdc112a090> of type 'SparseTensor' instead.
```
Does anyone know what I'm missing ?

Thanks

**Comment by KesterTong** [comment] 2018-05-03 19:59
I think the problem is that `original` is a `SparseTensor`.  This occurs when you use `ListColumnRepresentation`.  What kind of data is `original`?

**Comment by fabito** [comment] 2018-05-04 18:11
@KesterTong ,

`original` is `inputs['ethnic']` which is a `string`
I used to pass it directly to `string_to_int` and it was working fine.

```
outputs['ethnic'] = tft.string_to_int(inputs['ethnic'], vocab_filename='ethnic')
```

Now I need to group the categories differently and that's why I'm trying to apply the  `_group_ethnic` function.

**Comment by harshini-gadige** [comment] 2018-10-23 20:40
@KesterTong - Hi, any update on this issue ?

**Comment by harshini-gadige** [comment] 2018-11-16 19:37
> It's of type `FixedColumnRepresentation`.

@KesterTong  Any update ?

**Comment by KesterTong** [comment] 2018-11-16 21:36
It seems like "original" is a SparseTensor, could you provide a link to your full code including the Schema and preprocessing_fn so I can take another look

**Comment by hgadig** [comment] 2019-03-15 17:05
Closing as it is in "awaiting response" status for long time. Feel free to test with the latest versions and open a new issue provide details about the latest versions used. Thanks !

**Closed** 2019-03-15 17:06 UTC
Labels: stat:awaiting response, type:bug/performance
