### ISSUE TITLE
AttributeError: 'module' object has no attribute 'Context'

### ISSUE THREAD

**Issue by Alex-zhai** [tensorflow/transform#87] opened 2018-11-02 02:58 UTC
When I run sentiment_example.py script,  **AttributeError: 'module' object has no attribute 'Context'**  occured. Anybody else  had encountered this problem???

**Comment by zoyahav** [comment] 2018-11-02 14:34
Could you tell us which version of tensorflow-transform you have installed and are you using the sentiment_example.py that's currently at master?

Those should generally be in sync and you can find the corresponding example to the version you have installed by looking at this link:
https://github.com/tensorflow/transform/tree/v<version> (for example 0.11.0)

**Comment by cactusgame** [comment] 2018-11-14 11:22
it is may be caused by a mismatch version between tensorflow transform and your example code.

**Comment by harshini-gadige** [comment] 2018-11-16 19:44
@Alex-zhai  Any update ? Also, please provide the information asked above which helps us to look into this issue. Thanks !

**Comment by hgadig** [comment] 2019-03-13 17:41
Closing this issue as it is in "awaiting response" status for more than a week. Feel free to add your comments and we will reopen.

**Closed by hgadig** 2019-03-13 17:41 UTC
Labels: stat:awaiting response
