### ISSUE TITLE
"Table not initialized" error

### ISSUE THREAD

**Issue by jcomfort4** [tensorflow/transform#35] opened 2017-10-07 15:50 UTC
Consider the simple example:

```
graph = tf.Graph()
with graph.as_default():
    comma_separated = tf.constant(["hello, hello, test, random"], dtype=tf.string)
    words = tf.string_split(comma_separated, delimiter = ", ")
    indices = tft.string_to_int(words, top_k = 1)
    
sess = tf.InteractiveSession(graph=graph)
print(sess.run([indices]))
```

Results in the error:

```
FailedPreconditionError (see above for traceback): Table not initialized.
	 [[Node: hash_table_Lookup = LookupTableFind[Tin=DT_STRING, Tout=DT_INT64, _class=["loc:@string_to_index/hash_table"], _device="/job:localhost/replica:0/task:0/cpu:0"](string_to_index/hash_table, StringSplit:1, string_to_index/hash_table/Const)]]
```

I just ran pip install tensorflow-transform this morning so I believe tf is up to date. I'm guessing that maybe I am not up to date with the most recent tensorflow version that is needed? I am using tensorflow 1.2 because Google Cloud ML Engine does not yet support tensorflow 1.3. Is this the reason for the issue? I am trying to use TFT as a preprocessing script for my GCMLE experiment.

I separately got a warning that may also be related to the issue:

"WARNING:tensorflow:From /Users/user/anaconda/lib/python2.7/site-packages/tensorflow_transform/mappers.py:305: string_to_index_table_from_tensor (from tensorflow.contrib.lookup.lookup_ops) is deprecated and will be removed after 2017-04-10.
Instructions for updating:
Use `index_table_from_tensor`"

Any ideas what may be causing the issue?

**Comment by jcomfort4** [comment] 2017-10-07 16:03
I tested this with python 2.7, the latest pip install --upgrade tensorflow-transform and the latest pip install --upgrade tensorflow (which resulted in TF 1.3.0, git version 'v1.3.0-rc2-20-g0787eee') and I still got the same error.  Is there something that I am missing?

**Comment by elmer-garduno** [comment] 2017-10-10 08:07
Hi, TFT 0.10.0 works with TF 1.2 the code and samples on the github head only work with TF 1.3 did any of these combinations worked for you?

**Comment by jcomfort4** [comment] 2017-10-10 16:09
I ran these first with the following combinations:

tensorflow==1.2.1
tensorflow-transform==0.1.10

Is this tensorflow transform (from pip install tensorflow-transform) supposed to be working with TF 1.2.1? 

How would I get the version of tensorflow-transform that is compatible with TF 1.2? The reason that I need to use 1.2 is that Google Cloud ML Engine is only compatible with TF 1.2.

**Comment by elmer-garduno** [comment] 2017-10-11 16:13
Yes the following combination shoud work:

**Comment by jcomfort4** [comment] 2017-10-11 18:06
So it must be TF 1.2.0 and not TF 1.2.1? I am currently using TF 1.2.1 and Beam[GCP] 2.1.1 and TFT 0.1.10 and it is not working. It seems odd that TF 1.2.1 would cause the issues..

**Comment by katsiapis** [comment] 2017-10-21 20:36
Regarding the warnings you reported in your first post, please see our responses in https://github.com/tensorflow/transform/issues/34.

Regarding known compatibility matrix for Tensorflow Transform, please see
https://github.com/tensorflow/transform#compatible-versions

TF 1.2 (or 1.2.1)
Apache Beam [GCP] 2.1.1
TFT 0.1.10

should work (although it's not specifically part of the compatibility matrix).

Is it possible that there is some environment issue?
Could you post the result of `pipe freeze` for your environment?

Also take a look at the CloudML Samples (https://github.com/GoogleCloudPlatform/cloudml-samples/tree/master/criteo_tft) which showcase usage of

TF 1.3
Apache Beam [GCP] 2.1.1
TFT 0.1.10

(See https://github.com/GoogleCloudPlatform/cloudml-samples/blob/master/criteo_tft/requirements.txt)

/cc @KesterTong 
/cc @puneith

**Comment by katsiapis** [comment] 2017-10-21 20:39
I just also noticed that you are not using TFT as designed (eg I don't see preprocessing_fn etc in your code snippet).

On info regarding how to use TFT, please see the Getting Started Guide: https://github.com/tensorflow/transform/blob/master/getting_started.md

As well as the various TFT examples we provide: https://github.com/tensorflow/transform/tree/master/examples

@jcomfort4, if this answers your questions, feel free to Close this issue.

**Comment by jcomfort4** [comment] 2017-10-21 20:46
Thank you for the detailed response

`pip freeze` results in:
tensorflow==1.2.1
tensorflow-transform==0.1.10
apache-beam==2.1.1

The issue with the CloudML sample that uses TF 1.3 is that TF 1.3 is not supported by GCMLE as far as I have been told, so I am specifically trying to use TF 1.2 because that is all that is supported by GCMLE.

My code snippet was specifically designed to illustrate the error that I am facing. When trying to actually run this as part of a tensorflow experiment I would use a preprocessing function as they suggest, but that should have no effect on the error that I am seeing. As I see it, that is just wrapping the same tensor ops in a function. Even when I did that in my tensorflow experiment I ran into the same error, so I created a simplified sample to demonstrate the error (rather than somebody needing to run a large GCMLE experiment).  

I think the larger point is that @elmer-garduno suggested that my setup should work and it is not working, but for GCMLE I don't really have an alternative option?

**Comment by katsiapis** [comment] 2017-10-22 21:04
Tensorflow Transform code (like tft.string_to_int) is designed to only to run within a Function (the preprocessing_fn) that is passed to Analyze() or AnalyzeAndTransform().

Indeed TFT itself will take care of initializing tables and other state as part of its (Analyze) computation: https://github.com/tensorflow/transform/blob/v0.1.10/tensorflow_transform/beam/impl.py#L205

Are you able to run this example (which showcases use of tft.string_to_int): https://github.com/tensorflow/transform/blob/v0.1.10/examples/simple_example.py?

That should work with:
tensorflow==1.2.1
tensorflow-transform==0.1.10
apache-beam==2.1.1

I think the versioning discussion is a somewhat orthogonal discussion, but note that as long as you don't use any functionality that is new in TF 1.3 you should be able to run in CMLE with TF 1.2 (since semantic versioning guarantees that TF 1.3 is backwards compatible with TF 1.2).

**Comment by katsiapis** [comment] 2017-10-30 20:35
@jcomfort4, let us know if we can Close this (based on the info presented above).

**Comment by KesterTong** [comment] 2017-11-07 17:39
Regarding the table_not_initialized error, when using the Estimator API as done in our examples this should not occur.

However if you are consuming the output of tf.Transform in some other way, then you may need to call `tf.tables_initializer` and run that op yourself.

Basically what is going on is that tf.Transform uses "tables" to implement the hash-map from strings to ints, and these tables require initialization.  Specifically each table has an op that must be run once per session, before that table is used.  This is taken care of for you when you use the Estimator API, but if you don't you have to run these ops yourself.  You don't have to individually run each table initializer because TF stores them in a "collection" and `tf.tables_initializer` is an op that runs each of the table init ops by looking them up in the collection.

**Comment by katsiapis** [comment] 2017-12-12 16:57
@jcomfort4, we'll proceed to closing this issue as part of our triage process (since things seem to be working as intended?). If we misunderstood, feel free to reopen this Issue.

As an FYI, tf.transform 0.4 has been [released](https://github.com/tensorflow/transform/blob/v0.4.0/RELEASE.md) and it also includes updated examples, so consider also consulting those if you continue running into issues.

**Closed by katsiapis** 2017-12-12 16:57 UTC
