### ISSUE TITLE
Mean/Median value Imputation

### ISSUE THREAD

**Issue by jhoh10** [tensorflow/transform#131] opened 2019-07-18 19:00 UTC
Is there any plans to introduce imputation to tensorflow transform? Believe this could be very helpful, particularly mean and median value imputation.

------------------------------------------------------------
We will be adding imputation support soon.

_Originally posted by @sharifgamal in https://github.com/tensorflow/transform/issues/67#issuecomment-401363792_

**Comment by rmothukuru** [comment] 2019-07-19 08:03
@jhoh10 ,
Can you refer [this suggestion](https://github.com/tensorflow/transform/issues/78#issuecomment-427919062) from Kester. This is the [link](https://github.com/tensorflow/transform/blob/master/examples/census_example.py#L145) of the example code snippet.

**Comment by rmothukuru** [comment] 2019-07-29 09:31
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by rmothukuru** 2019-07-29 09:31 UTC
Labels: stat:awaiting response, type:support

**Comment by jhoh10** [comment] 2019-07-29 15:39
sorry for the lack of response. I've been struggling to get this working. Although I was able to implement the workaround above, it doesn't seem like a very intuitive/straightforward way of doing things. I am currently struggling on how to get model serving working using this approach, as it expects each sparse feature to represented as a list.

**Comment by jhoh10** [comment] 2019-08-29 19:22
if someone could link to source code of an ML flow where:
- tensorflow transform is used
- capable of imputing missing numerical column values
- works on ml engine local predict by feeding data in via json

This seem like this type of thing should be extremely common - I'm surprised I can't find it anywhere. It would be immensely helpful.

**Comment by amarchin** [comment] 2020-02-03 14:23
Any update on this?

**Comment by zoyahav** [comment] 2020-02-03 15:39
Could you follow the example in https://github.com/tensorflow/transform/issues/152?
Could you also expand on what the issue is with serving?
