### ISSUE TITLE
count_per_key not working with SparseTensor input

### ISSUE THREAD

**Issue by JakeTheWise** [tensorflow/transform#176] opened 2020-05-18 22:18 UTC
tensorflow==2.1.0
tensorflow-data-validation==0.22.0
tensorflow-transform==0.22.0

Trying to compute `tft.count_per_key` on a `tf.SparseTensor` gives an `AttributeError: 'SparseTensor' object has no attribute 'set_shape'` even though the documentation says it will work with a sparse tensor.

**Comment by rmothukuru** [comment] 2020-05-19 08:24
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by JakeTheWise** [comment] 2020-05-19 14:26
```python
def preprocessing_fn(inputs):
    vocab, count = tft.count_per_key(inputs['my_feature'])
    return ...
```
@rmothukuru

**Comment by zoyahav** [comment] 2020-05-26 12:30
Looks like reduce_batch_count_or_sum_per_key doesn't support a sparse key:
https://github.com/tensorflow/transform/blob/9594a48886cdf66427e591f6b708ad522e42e3a7/tensorflow_transform/tf_utils.py#L361
We'll have to fix that.

**Comment by zoyahav** [comment] 2020-05-27 13:46
With commit https://github.com/tensorflow/transform/commit/752b975cc0f24679b78b00ccf665e701c85a3d25 this should be fixed on github master and nightly[1] starting tomorrow.
@JakeTheWise will you be able to give this a try?

Closing this issue for now, we can re-open if there are still remaining issues.

[1] https://test.pypi.org/project/tensorflow-transform/

**Closed by zoyahav** 2020-05-27 13:46 UTC
Labels: stat:awaiting tensorflower, type:bug
