### ISSUE TITLE
Custom Mapping Function lookup_fn 

### ISSUE THREAD

**Issue by erikinfo** [tensorflow/transform#178] opened 2020-05-30 13:48 UTC
Hello, 

i'm facing the same problem with probably a newer version (TF 2.0) since tf.contrib.lookup.index_table_from_file is not available. 

I've tried it with this: 
`table = tf.lookup.StaticHashTable(tf.lookup.TextFileInitializer(vocab_filename, tf.string, 0, tf.int64, 1, delimiter="!"),7)`

but got
OperatorNotAllowedInGraphError: iterating over `tf.Tensor` is not allowed in Graph execution. Use Eager execution or decorate this function with @tf.function.

What is the problem here and what lookups could i use instead? 
I want to map strings to ints with a vocabulary file(txt).
And more minor: When using lookup_fn it says "return a lookup op along with the table size"? What would be an accurate return function? 

> Note that tft.compute_and_apply_vocabulary (and the underlying analyzer tft.vocabulary), computes a vocabulary over the data.
> 
> Instead of using tft.compute_and_apply_vocabulary which just performs a lookup in the vocabulary and returns the index for each value, you could use tft.vocabulary and tft.apply_vocabulary with a custom lookup_fn:
> https://www.tensorflow.org/tfx/transform/api_docs/python/tft/apply_vocabulary
> 
> in the preprocessing_fn:
> 
> ```
> def compute_mapped_value(x):
>   ....
> def lookup_fn(key, vocab_filename):
>   table = tf.lookup.index_table_from_file(vocab_filename, ...)
>   value = table.lookup(key)
>   return compute_mapped_value(value)
> vocabulary_filename = tft.vocabulary(x, ...)
> x_numerical = tft.apply_vocabulary(x, vocabulary_filename, lookup_fn=lookup_fn, ...)
> ```
> 
> Would that work for your use case?

_Originally posted by @wed0itagain in https://github.com/tensorflow/transform/issues/147#issuecomment-636333293_

**Comment by zoyahav** [comment] 2020-06-02 09:28
Please provide your full preprocessing_fn, and the full stacktrace so that we can give you guidance.

**Comment by wed0itagain** [comment] 2020-06-02 10:31
Following the guidance in the tutorial i made this: 

`%%skip_for_export
%%writefile {_X_transform_module_file}

import tensorflow as tf
import tensorflow_transform as tft

import X_constants

_VOCAB_MAPFEATURE_KEYS = food_constants.VOCAB_MAPFEATURE_KEYS



`

**Comment by wed0itagain** [comment] 2020-06-02 11:04
```
%%skip_for_export
%%writefile {_XYZ_transform_module_file}

import tensorflow as tf
import tensorflow_transform as tft

import XYZ_constants
_VOCAB_MAPFEATURE_KEYS = XYZ_constants.VOCAB_MAPFEATURE_KEYS
vocab_filename=XYZ_constants.vocab_filename

def preprocessing_fn(inputs):

   outputs = {}

   for key in _VOCAB_MAPFEATURE_KEYS:
       vocabulary_filename=tft.vocabulary(inputs[key],top_k=150000)   
'''''''outputs[_transformed_name(key)]=tft.apply_vocabulary((_fill_in_missing(inputs[key])),vocabulary_filename,num_oov_buckets=_OOV_SIZE,lookup_fn=lookup_fn)





      


def _fill_in_missing(x):
  """Replace missing values in a SparseTensor.
  Fills in missing values of `x` with '' or 0, and converts to a dense tensor.
  Args:
    x: A `SparseTensor` of rank 2.  Its dense shape should have size at most 1
      in the second dimension.
  Returns:
    A rank 1 tensor where missing values of `x` have been filled in.
  """
  default_value = '' if x.dtype == tf.string else 0
  return tf.squeeze(
      tf.sparse.to_dense(
          tf.SparseTensor(x.indices, x.values, [x.dense_shape[0], 1]),
          default_value),
      axis=1)

def lookup_fn(key,vocab_filename): 
  table = tf.lookup.StaticVocabularyTable(tf.lookup.TextFileInitializer(vocab_filename, tf.string, 0, tf.int64, 1, delimiter="!"),7) 
  value = table.lookup(key)
  return value
`
```
vocab_filename points to a text file which has the format [string]![int] like a dictionary. 
```



`Error
		OperatorNotAllowedInGraphError
		---------------------------------------------------------------------------
		OperatorNotAllowedInGraphError            Traceback (most recent call last)
		<ipython-input-58-e892fd409daf> in <module>()
		      3     schema=schema_gen.outputs['schema'],
		      4     module_file=os.path.abspath(_XYZ_transform_module_file))
		----> 5 context.run(transform)
		
		/usr/local/lib/python3.6/dist-packages/tfx/orchestration/experimental/interactive/interactive_context.py in run_if_ipython(*args, **kwargs)
		     64       # __IPYTHON__ variable is set by IPython, see
		     65       # https://ipython.org/ipython-doc/rel-0.10.2/html/interactive/reference.html#embedding-ipython.
		---> 66       return fn(*args, **kwargs)
		     67     else:
		     68       absl.logging.warning(
		
		/usr/local/lib/python3.6/dist-packages/tfx/orchestration/experimental/interactive/interactive_context.py in run(self, component, enable_cache, beam_pipeline_args)
		    166         component, pipeline_info, driver_args, metadata_connection,
		    167         beam_pipeline_args, additional_pipeline_args)
		--> 168     execution_id = launcher.launch().execution_id
		    169 
		    170     return execution_result.ExecutionResult(
		
		/usr/local/lib/python3.6/dist-packages/tfx/orchestration/launcher/base_component_launcher.py in launch(self)
		    203                          execution_decision.input_dict,
		    204                          execution_decision.output_dict,
		--> 205                          execution_decision.exec_properties)
		    206 
		    207     absl.logging.info('Running publisher for %s',
		
		/usr/local/lib/python3.6/dist-packages/tfx/orchestration/launcher/in_process_component_launcher.py in _run_executor(self, execution_id, input_dict, output_dict, exec_properties)
		     65         executor_context)  # type: ignore
		     66 
		---> 67     executor.Do(input_dict, output_dict, exec_properties)
		
		/usr/local/lib/python3.6/dist-packages/tfx/components/transform/executor.py in Do(self, input_dict, output_dict, exec_properties)
		    389       label_outputs[labels.CACHE_OUTPUT_PATH_LABEL] = cache_output
		    390     status_file = 'status_file'  # Unused
		--> 391     self.Transform(label_inputs, label_outputs, status_file)
		    392     absl.logging.debug('Cleaning up temp path %s on executor success',
		    393                        temp_path)
		
		/usr/local/lib/python3.6/dist-packages/tfx/components/transform/executor.py in Transform(***failed resolving arguments***)
		    908     # order to fail faster if it fails.
		    909     analyze_input_columns = tft.get_analyze_input_columns(
		--> 910         preprocessing_fn, feature_spec_or_typespecs)
		    911 
		    912     if not compute_statistics and not materialize_output_paths:
		
		/usr/local/lib/python3.6/dist-packages/tensorflow_transform/inspect_preprocessing_fn.py in get_analyze_input_columns(preprocessing_fn, specs)
		     56     input_signature = impl_helper.batched_placeholders_from_specs(
		     57         specs)
		---> 58     _ = preprocessing_fn(input_signature.copy())
		     59 
		     60     tensor_sinks = graph.get_collection(analyzer_nodes.TENSOR_REPLACEMENTS)
		
		/content/XYZ_transform.py in preprocessing_fn(inputs)
		     40   for key in _VOCAB_MAPFEATURE_KEYS:
		     41     vocabulary_filename=tft.vocabulary(inputs[key],top_k=150000)
		---> 42     outputs[_transformed_name(key)] = tft.apply_vocabulary((_fill_in_missing(inputs[key])),vocabulary_filename,num_oov_buckets=_OOV_SIZE,lookup_fn=lookup_fn)
		     43 
		     44   return outputs
		
		/usr/local/lib/python3.6/dist-packages/tensorflow_transform/common.py in wrapped_fn(*args, **kwargs)
		     74             collection.append(collections.Counter())
		     75           collection[0][fn.__name__] += 1
		---> 76           return fn(*args, **kwargs)
		     77       else:
		     78         return fn(*args, **kwargs)
		
		/usr/local/lib/python3.6/dist-packages/tensorflow_transform/mappers.py in apply_vocabulary(x, deferred_vocab_filename_tensor, default_value, num_oov_buckets, lookup_fn, name)
		    833 
		    834     if lookup_fn:
		--> 835       result, table_size = lookup_fn(x, deferred_vocab_filename_tensor)
		    836     else:
		    837       if (deferred_vocab_filename_tensor is None
		
		/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py in __iter__(self)
		    537   def __iter__(self):
		    538     if not context.executing_eagerly():
		--> 539       self._disallow_iteration()
		    540 
		    541     shape = self._shape_tuple()
		
		/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py in _disallow_iteration(self)
		    533     else:
		    534       # Default: V1-style Graph execution.
		--> 535       self._disallow_in_graph_mode("iterating over `tf.Tensor`")
		    536 
		    537   def __iter__(self):
		
		/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py in _disallow_in_graph_mode(self, task)
		    513     raise errors.OperatorNotAllowedInGraphError(
		    514         "{} is not allowed in Graph execution. Use Eager execution or decorate"
		--> 515         " this function with @tf.function.".format(task))
		    516 
		    517   def _disallow_bool_casting(self):
		
		OperatorNotAllowedInGraphError: iterating over `tf.Tensor` is not allowed in Graph execution. Use Eager execution or decorate this function with @tf.function.
	Stream
		INFO:absl:Running driver for Transform
		INFO:absl:MetadataStore with DB connection initialized
		INFO:absl:Running executor for Transform`

**Comment by zoyahav** [comment] 2020-06-02 11:52
The issue is that `_fill_in_missing` should be returning a tuple of (lookup result, table_size).
See the documentation for lookup_fn here:
https://www.tensorflow.org/tfx/transform/api_docs/python/tft/apply_vocabulary

**Comment by zoyahav** [comment] 2020-06-02 11:53
The issue is that `lookup_fn` should be returning a tuple of (lookup result, table_size).
See the documentation for lookup_fn here:
https://www.tensorflow.org/tfx/transform/api_docs/python/tft/apply_vocabulary

**Comment by wed0itagain** [comment] 2020-06-02 13:02
Okay thank you! I still get an error sadly... and can't find an solution 
```
@tf.function   
def lookup_fn(key,vocab_filename): 
  table = tf.lookup.StaticHashTable(tf.lookup.TextFileInitializer(vocab_filename, tf.string, 0, tf.int64, 1, delimiter="!"),7) 
  value=table.lookup(key)
  return (value,125)

```
```
`
_UnexpectedTableError: An unexpected initializable table was encountered (name: "hash_table"
op: "HashTableV2"
attr {
  key: "container"
  value {
    s: ""
  }
}
attr {
  key: "key_dtype"
  value {
    type: DT_STRING
  }
}
attr {
  key: "shared_name"
  value {
    s: "hash_table_Tensor(\"vocab_filename:0\", shape=(), dtype=string)_0_1"
  }
}
attr {
  key: "use_node_name_sharing"
  value {
    b: false
  }
}
attr {
  key: "value_dtype"
  value {
    type: DT_INT64
  }
}
)

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow_transform/graph_tools.py in wrapper(self, tensor_or_op)
    144             'adding an initializable table without adding its initializer to '
    145             'the collection tf.GraphKeys.TABLE_INITIALIZERS'.format(
--> 146                 tensor_or_op, e.op))
    147 
    148   return wrapper

ValueError: The tensor_or_op Tensor("apply_vocab/StatefulPartitionedCall:0", shape=(None,), dtype=int64) depended on an initializable table (name: "hash_table"
op: "HashTableV2"
attr {
  key: "container"
  value {
    s: ""
  }
}
attr {
  key: "key_dtype"
  value {
    type: DT_STRING
  }
}
attr {
  key: "shared_name"
  value {
    s: "hash_table_Tensor(\"vocab_filename:0\", shape=(), dtype=string)_0_1"
  }
}
attr {
  key: "use_node_name_sharing"
  value {
    b: false
  }
}
attr {
  key: "value_dtype"
  value {
    type: DT_INT64
  }
}
) that was not tracked by the graph analysis.  This may be caused by adding an initializable table without adding its initializer to the collection tf.GraphKeys.TABLE_INITIALIZERS_UnexpectedTableError: An unexpected initializable table was encountered (name: "hash_table"
op: "HashTableV2"
attr {
  key: "container"
  value {
    s: ""
  }
}
attr {
  key: "key_dtype"
  value {
    type: DT_STRING
  }
}
attr {
  key: "shared_name"
  value {
    s: "hash_table_Tensor(\"vocab_filename:0\", shape=(), dtype=string)_0_1"
  }
}
attr {
  key: "use_node_name_sharing"
  value {
    b: false
  }
}
attr {
  key: "value_dtype"
  value {
    type: DT_INT64
  }
}
)

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow_transform/graph_tools.py in wrapper(self, tensor_or_op)
    144             'adding an initializable table without adding its initializer to '
    145             'the collection tf.GraphKeys.TABLE_INITIALIZERS'.format(
--> 146                 tensor_or_op, e.op))
    147 
    148   return wrapper

ValueError: The tensor_or_op Tensor("apply_vocab/StatefulPartitionedCall:0", shape=(None,), dtype=int64) depended on an initializable table (name: "hash_table"
op: "HashTableV2"
attr {
  key: "container"
  value {
    s: ""
  }
}
attr {
  key: "key_dtype"
  value {
    type: DT_STRING
  }
}
attr {
  key: "shared_name"
  value {
    s: "hash_table_Tensor(\"vocab_filename:0\", shape=(), dtype=string)_0_1"
  }
}
attr {
  key: "use_node_name_sharing"
  value {
    b: false
  }
}
attr {
  key: "value_dtype"
  value {
    type: DT_INT64
  }
}
) that was not tracked by the graph analysis.  This may be caused by adding an initializable table without adding its initializer to the collection tf.GraphKeys.TABLE_INITIALIZERS`

**Comment by wed0itagain** [comment] 2020-06-02 13:36
Thank you

I'm still getting an error

```
@tf.function
def lookup_fn(key,vocab_filename): 
  table = tf.lookup.StaticHashTable(tf.lookup.TextFileInitializer(vocab_filename, tf.string, 0, tf.int64, 1, delimiter="!"),7) 
  value = table.lookup(key)
  return value
```

I don't understand how to use the .initialize() argument properly described in the TextFileInitializer [here](https://www.tensorflow.org/api_docs/python/tf/lookup/TextFileInitializer)


The error: 

```
INFO:absl:Running driver for Transform
INFO:absl:MetadataStore with DB connection initialized
INFO:absl:Running executor for Transform
---------------------------------------------------------------------------
_UnexpectedTableError                     Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow_transform/graph_tools.py in wrapper(self, tensor_or_op)
    119     try:
--> 120       return func(self, tensor_or_op)
    121     except _UnexpectedPlaceholderError as e:

13 frames
_UnexpectedTableError: An unexpected initializable table was encountered (name: "hash_table"
op: "HashTableV2"
attr {
  key: "container"
  value {
    s: ""
  }
}
attr {
  key: "key_dtype"
  value {
    type: DT_STRING
  }
}
attr {
  key: "shared_name"
  value {
    s: "hash_table_Tensor(\"vocab_filename:0\", shape=(), dtype=string)_0_1"
  }
}
attr {
  key: "use_node_name_sharing"
  value {
    b: false
  }
}
attr {
  key: "value_dtype"
  value {
    type: DT_INT64
  }
}
)

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow_transform/graph_tools.py in wrapper(self, tensor_or_op)
    144             'adding an initializable table without adding its initializer to '
    145             'the collection tf.GraphKeys.TABLE_INITIALIZERS'.format(
--> 146                 tensor_or_op, e.op))
    147 
    148   return wrapper

ValueError: The tensor_or_op Tensor("apply_vocab/StatefulPartitionedCall:0", shape=(None,), dtype=int64) depended on an initializable table (name: "hash_table"
op: "HashTableV2"
attr {
  key: "container"
  value {
    s: ""
  }
}
attr {
  key: "key_dtype"
  value {
    type: DT_STRING
  }
}
attr {
  key: "shared_name"
  value {
    s: "hash_table_Tensor(\"vocab_filename:0\", shape=(), dtype=string)_0_1"
  }
}
attr {
  key: "use_node_name_sharing"
  value {
    b: false
  }
}
attr {
  key: "value_dtype"
  value {
    type: DT_INT64
  }
}
) that was not tracked by the graph analysis.  This may be caused by adding an initializable table without adding its initializer to the collection tf.GraphKeys.TABLE_INITIALIZERS
```


Can you please provide me some sample code how to do it?

**Comment by zoyahav** [comment] 2020-06-02 15:15
Your usage of the initializer seems fine actually.
Could you try it without wrapping lookup_fn in @tf.function?
This is likely a TF version 1.x vs. 2.x difference where collections are getting deprecated in 2.x.

**Comment by wed0itagain** [comment] 2020-06-03 10:26
Thank you, i finally got it working. 

For future reference this is what i did (this might not be the smartest solution but atleast it works):

return (value,tf.constant(LINENUMBER))

and i removed top_k when creating tft.vocabulary. I guess this contradicts the custom use of the lookup_fn.

**Comment by zoyahav** [comment] 2020-06-03 10:32
You should be able to do this instead:
```
return (value, table.size())
```

**Comment by wed0itagain** [comment] 2020-06-03 11:25
Now i hopped into this problem. I don't get why it's so picky about Eggs and Water. They are somewhere in my dataset and even after i introduced them in the vocab file i still got the error. 
```
INFO:tensorflow:Saver not created because there are no variables in the graph to restore
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py in _do_call(self, fn, *args)
   1366     try:
-> 1367       return fn(*args)
   1368     except errors.OpError as e:

69 frames
InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Invalid number of columns in /tmp/tfx-interactive-2020-06-03T11_14_49.323950-15nq1tmo/Transform/transform_graph/5/.temp_path/tftransform_tmp/6e28eef4edb847e29469e39d599c7863/assets/vocab_vocabulary line 0 (['eggs', 'water']) : expected 1 got 1
	 [[{{node transform/transform/apply_vocab/text_file_init/InitializeTableFromTextFileV2}}]]
	 [[GroupCrossDeviceControlEdges_0/init_all_tables/_2]]
  (1) Invalid argument: Invalid number of columns in /tmp/tfx-interactive-2020-06-03T11_14_49.323950-15nq1tmo/Transform/transform_graph/5/.temp_path/tftransform_tmp/6e28eef4edb847e29469e39d599c7863/assets/vocab_vocabulary line 0 (['eggs', 'water']) : expected 1 got 1
	 [[{{node transform/transform/apply_vocab/text_file_init/InitializeTableFromTextFileV2}}]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

InvalidArgumentError                      Traceback (most recent call last)
InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Invalid number of columns in /tmp/tfx-interactive-2020-06-03T11_14_49.323950-15nq1tmo/Transform/transform_graph/5/.temp_path/tftransform_tmp/6e28eef4edb847e29469e39d599c7863/assets/vocab_vocabulary line 0 (['eggs', 'water']) : expected 1 got 1
	 [[node transform/transform/apply_vocab/text_file_init/InitializeTableFromTextFileV2 (defined at /local/lib/python3.6/dist-packages/tensorflow_transform/saved/saved_transform_io.py:251) ]]
	 [[GroupCrossDeviceControlEdges_0/init_all_tables/_2]]
  (1) Invalid argument: Invalid number of columns in /tmp/tfx-interactive-2020-06-03T11_14_49.323950-15nq1tmo/Transform/transform_graph/5/.temp_path/tftransform_tmp/6e28eef4edb847e29469e39d599c7863/assets/vocab_vocabulary line 0 (['eggs', 'water']) : expected 1 got 1
	 [[node transform/transform/apply_vocab/text_file_init/InitializeTableFromTextFileV2 (defined at /local/lib/python3.6/dist-packages/tensorflow_transform/saved/saved_transform_io.py:251) ]]
0 successful operations.
0 derived errors ignored.

Errors may have originated from an input operation.
Input Source operations connected to node transform/transform/apply_vocab/text_file_init/InitializeTableFromTextFileV2:
 Identity_2 (defined at /local/lib/python3.6/dist-packages/tensorflow_transform/saved/saved_transform_io.py:181)

Input Source operations connected to node transform/transform/apply_vocab/text_file_init/InitializeTableFromTextFileV2:
 Identity_2 (defined at /local/lib/python3.6/dist-packages/tensorflow_transform/saved/saved_transform_io.py:181)

Original stack trace for 'transform/transform/apply_vocab/text_file_init/InitializeTableFromTextFileV2':
  File "/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/lib/python3.6/concurrent/futures/thread.py", line 69, in _worker
    work_item.run()
  File "/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/local/lib/python3.6/dist-packages/apache_beam/runners/portability/fn_api_runner.py", line 1801, in <lambda>
    part, expected_outputs), part_inputs):
  File "/local/lib/python3.6/dist-packages/apache_beam/runners/portability/fn_api_runner.py", line 1737, in process_bundle
    result_future = self._worker_handler.control_conn.push(process_bundle_req)
  File "/local/lib/python3.6/dist-packages/apache_beam/runners/portability/fn_api_runner.py", line 1150, in push
    response = self.worker.do_instruction(request)
  File "/local/lib/python3.6/dist-packages/apache_beam/runners/worker/sdk_worker.py", line 360, in do_instruction
    request.instruction_id)
  File "/local/lib/python3.6/dist-packages/apache_beam/runners/worker/sdk_worker.py", line 386, in process_bundle
    bundle_processor.process_bundle(instruction_id))
  File "/local/lib/python3.6/dist-packages/apache_beam/runners/worker/bundle_processor.py", line 663, in process_bundle
    data.transform_id].process_encoded(data.data)
  File "/local/lib/python3.6/dist-packages/apache_beam/runners/worker/bundle_processor.py", line 143, in process_encoded
    self.output(decoded_value)
  File "/local/lib/python3.6/dist-packages/apache_beam/transforms/core.py", line 1349, in <lambda>
    wrapper = lambda x: [fn(x)]
  File "/local/lib/python3.6/dist-packages/tensorflow_transform/beam/impl.py", line 673, in _infer_metadata_from_saved_model
    saved_model_dir, {}))
  File "/local/lib/python3.6/dist-packages/tensorflow_transform/saved/saved_transform_io.py", line 408, in partially_apply_saved_transform_internal
    saved_model_dir, logical_input_map, tensor_replacement_map)
  File "/local/lib/python3.6/dist-packages/tensorflow_transform/saved/saved_transform_io.py", line 251, in _partially_apply_saved_transform_impl
    input_map=input_map)
  File "/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py", line 1453, in import_meta_graph
    **kwargs)[0]
  File "/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py", line 1477, in _import_meta_graph_with_return_elements
    **kwargs))
  File "/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/meta_graph.py", line 797, in import_scoped_meta_graph_with_return_elements
    return_elements=return_elements)
  File "/local/lib/python3.6/dist-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/importer.py", line 405, in import_graph_def
    producer_op_list=producer_op_list)
  File "/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/importer.py", line 513, in _import_graph_def_internal
    _ProcessNewOps(graph)
  File "/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/importer.py", line 243, in _ProcessNewOps
    for new_op in graph._add_new_tf_operations(compute_devices=False):  # pylint: disable=protected-access
  File "/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 3459, in _add_new_tf_operations
    for c_op in c_api_util.new_tf_operations(self)
  File "/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 3459, in <listcomp>
    for c_op in c_api_util.new_tf_operations(self)
  File "/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 3347, in _create_op_from_tf_operation
    ret = Operation(c_op, self)
  File "/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 1756, in __init__
    self._traceback = tf_stack.extract_stack()


During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py in _do_call(self, fn, *args)
   1384                     '\nsession_config.graph_options.rewrite_options.'
   1385                     'disable_meta_optimizer = True')
-> 1386       raise type(e)(node_def, op, message)
   1387 
   1388   def _extend_graph(self):

RuntimeError: tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Invalid number of columns in /tmp/tfx-interactive-2020-06-03T11_14_49.323950-15nq1tmo/Transform/transform_graph/5/.temp_path/tftransform_tmp/6e28eef4edb847e29469e39d599c7863/assets/vocab_vocabulary line 0 (['eggs', 'water']) : expected 1 got 1
	 [[node transform/transform/apply_vocab/text_file_init/InitializeTableFromTextFileV2 (defined at /local/lib/python3.6/dist-packages/tensorflow_transform/saved/saved_transform_io.py:251) ]]
	 [[GroupCrossDeviceControlEdges_0/init_all_tables/_2]]
  (1) Invalid argument: Invalid number of columns in /tmp/tfx-interactive-2020-06-03T11_14_49.323950-15nq1tmo/Transform/transform_graph/5/.temp_path/tftransform_tmp/6e28eef4edb847e29469e39d599c7863/assets/vocab_vocabulary line 0 (['eggs', 'water']) : expected 1 got 1
	 [[node transform/transform/apply_vocab/text_file_init/InitializeTableFromTextFileV2 (defined at /local/lib/python3.6/dist-packages/tensorflow_transform/saved/saved_transform_io.py:251) ]]
0 successful operations.
0 derived errors ignored.

Errors may have originated from an input operation.
Input Source operations connected to node transform/transform/apply_vocab/text_file_init/InitializeTableFromTextFileV2:
 Identity_2 (defined at /local/lib/python3.6/dist-packages/tensorflow_transform/saved/saved_transform_io.py:181)

Input Source operations connected to node transform/transform/apply_vocab/text_file_init/InitializeTableFromTextFileV2:
 Identity_2 (defined at /local/lib/python3.6/dist-packages/tensorflow_transform/saved/saved_transform_io.py:181)

Original stack trace for 'transform/transform/apply_vocab/text_file_init/InitializeTableFromTextFileV2':
  File "/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/lib/python3.6/concurrent/futures/thread.py", line 69, in _worker
    work_item.run()
  File "/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/local/lib/python3.6/dist-packages/apache_beam/runners/portability/fn_api_runner.py", line 1801, in <lambda>
    part, expected_outputs), part_inputs):
  File "/local/lib/python3.6/dist-packages/apache_beam/runners/portability/fn_api_runner.py", line 1737, in process_bundle
    result_future = self._worker_handler.control_conn.push(process_bundle_req)
  File "/local/lib/python3.6/dist-packages/apache_beam/runners/portability/fn_api_runner.py", line 1150, in push
    response = self.worker.do_instruction(request)
  File "/local/lib/python3.6/dist-packages/apache_beam/runners/worker/sdk_worker.py", line 360, in do_instruction
    request.instruction_id)
  File "/local/lib/python3.6/dist-packages/apache_beam/runners/worker/sdk_worker.py", line 386, in process_bundle
    bundle_processor.process_bundle(instruction_id))
  File "/local/lib/python3.6/dist-packages/apache_beam/runners/worker/bundle_processor.py", line 663, in process_bundle
    data.transform_id].process_encoded(data.data)
  File "/local/lib/python3.6/dist-packages/apache_beam/runners/worker/bundle_processor.py", line 143, in process_encoded
    self.output(decoded_value)
  File "/local/lib/python3.6/dist-packages/apache_beam/transforms/core.py", line 1349, in <lambda>
    wrapper = lambda x: [fn(x)]
  File "/local/lib/python3.6/dist-packages/tensorflow_transform/beam/impl.py", line 673, in _infer_metadata_from_saved_model
    saved_model_dir, {}))
  File "/local/lib/python3.6/dist-packages/tensorflow_transform/saved/saved_transform_io.py", line 408, in partially_apply_saved_transform_internal
    saved_model_dir, logical_input_map, tensor_replacement_map)
  File "/local/lib/python3.6/dist-packages/tensorflow_transform/saved/saved_transform_io.py", line 251, in _partially_apply_saved_transform_impl
    input_map=input_map)
  File "/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py", line 1453, in import_meta_graph
    **kwargs)[0]
  File "/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py", line 1477, in _import_meta_graph_with_return_elements
    **kwargs))
  File "/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/meta_graph.py", line 797, in import_scoped_meta_graph_with_return_elements
    return_elements=return_elements)
  File "/local/lib/python3.6/dist-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/importer.py", line 405, in import_graph_def
    producer_op_list=producer_op_list)
  File "/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/importer.py", line 513, in _import_graph_def_internal
    _ProcessNewOps(graph)
  File "/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/importer.py", line 243, in _ProcessNewOps
    for new_op in graph._add_new_tf_operations(compute_devices=False):  # pylint: disable=protected-access
  File "/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 3459, in _add_new_tf_operations
    for c_op in c_api_util.new_tf_operations(self)
  File "/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 3459, in <listcomp>
    for c_op in c_api_util.new_tf_operations(self)
  File "/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 3347, in _create_op_from_tf_operation
    ret = Operation(c_op, self)
  File "/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 1756, in __init__
    self._traceback = tf_stack.extract_stack() [while running 'Analyze/ComputeDeferredMetadata']```

**Comment by zoyahav** [comment] 2020-06-03 11:42
> introduced them in the vocab file

What do you mean by that? Please include code changes.

**Comment by wed0itagain** [comment] 2020-06-03 11:59
I wrote them down in the Mapping Text File i created (which is missing some values) that is needed for TextFileInit ([string]![int]). Still the error occured. 


```
%%skip_for_export
%%writefile {_XYZ_transform_module_file}

import tensorflow as tf
import tensorflow_transform as tft

import XYZ_constants
_VOCAB_MAPFEATURE_KEYS = XYZ_constants.VOCAB_MAPFEATURE_KEYS
vocab_filename=XYZ_constants.vocab_filename
_OOV_SIZE = XYZ_constants.OOV_SIZE


def preprocessing_fn(inputs):

   outputs = {}

   for key in _VOCAB_MAPFEATURE_KEYS:
       vocabulary_filename=tft.vocabulary(inputs[key])   
'''''''outputs[_transformed_name(key)]=tft.apply_vocabulary((_fill_in_missing(inputs[key])),vocabulary_filename,num_oov_buckets=_OOV_SIZE,lookup_fn=lookup_fn)


def lookup_fn(key,vocab_filename): 
  table = tf.lookup.StaticHashTable(tf.lookup.TextFileInitializer(vocab_filename, tf.string, 0, tf.int64, 1, delimiter="!"),7) 
  value = table.lookup(key)
  return (value,table.size())
```

**Comment by zoyahav** [comment] 2020-06-03 12:50
What is the Mapping Text File? where is it used and what are its contents?

**Comment by wed0itagain** [comment] 2020-06-03 13:18
Part of the look_up fn: 
 table = tf.lookup.StaticHashTable(tf.lookup.TextFileInitializer(**_vocab_filename(.txt)_**, tf.string, 0, tf.int64, 1, delimiter="!"),7) 

In this text file i have mapped for example:
apple!1.0
...

around 127 words (they don't represent the dataset (tft.vocabulary) totally and i dont know if thats a problem, but i guess they would get mapped to default_value=7 otherways (as seen above).

**Comment by zoyahav** [comment] 2020-06-03 14:12
Is it formatted exactly the same as the vocab produced by tft.vocabulary? (including same new line characters)
This should generally work, but at this point your issue is a pure TensorFlow issue, I suggest trying to make the table work in a python terminal directly.

**Comment by wed0itagain** [comment] 2020-06-07 12:49
When running it directly in a python terminal it works as expected.  So the problem must be the different formats (i did not think of using the same format)


> we are currently writing the vocabularies as text files. This behavior will likely be fixed/improved in the future. (...)
The unique values are sorted by decreasing frequency and then reverse lexicographical order (e.g. [('a', 5), ('c', 3), ('b', 3)]).

What's the tft.vocabulary text format and its new line characters? 

I cant find anything to this sorry

**Comment by zoyahav** [comment] 2020-06-08 15:50
It's just text entries separated by new line characters. Perhaps see if you're using a different style of new line characters (e.g. windows vs. linux).
I don't understand the question above. If you're not using tft.vocabulary to produce the vocabulary, you shouldn't be using tft.apply_vocabulary to apply it.
You can instead use the table directly in your preprocessing_fn.

**Comment by arghyaganguly** [comment] 2021-04-27 11:10
Closing this due to inactivity.Please feel free to reopen with new questions/insights based on above comment trace.

**Closed by arghyaganguly** 2021-04-27 11:10 UTC
Labels: stat:awaiting response, type:support
