### ISSUE TITLE
The saved path to vocabulary file is absolute

### ISSUE THREAD

**Issue by wsuchy** [tensorflow/transform#140] opened 2019-09-19 17:35 UTC
In my `preprocessing_fn` I am defining a vocabulary using `tft.compute_and_apply_vocabulary`. Unfortunately when I save the graph, it contains an absolute reference to the vocab file: `/var/folders/h3/zt26x1d93hq49vff996w04pc0000gq/T/tmpkj5__87_/tftransform_tmp/workclass` in the generated pb file.
How do I initialize the hash table back given I the vocab file is in different location?

**Comment by wsuchy** [comment] 2019-09-19 18:46
Also when I load back my graph from pb file, there is no way to initialize the lookup tables (even if the file is present).  
Neither calling `tf.initializers.tables_initializer(name='init_all_tables')` or `sess.graph.get_operation_by_name("import/transform/workclass/apply_vocab/string_to_index/hash_table/table_init").run(...)` solves the issue and I keep getting error:
```
FailedPreconditionError: Table not initialized.
```

**Comment by zoyahav** [comment] 2019-09-19 23:59
How do you save the graph, and then how do you load it? can you please provide the relevant snippets of code?

**Comment by wsuchy** [comment] 2019-09-20 16:40
I've prepared a notebook, it's a modified version of the tutorial code:
https://github.com/wsuchy/tf_transform_playground/blob/master/tf-transform-example.ipynb

**Comment by wsuchy** [comment] 2019-09-30 18:04
@zoyahav were you able to replicate the issue?

**Comment by zoyahav** [comment] 2019-09-30 19:09
@wsuchy, any reason why you're not using  [tft.TFTransformOutput](https://github.com/tensorflow/transform/blob/master/tensorflow_transform/output_wrapper.py) to load and use the saved model (and are instead parsing the SavedModel manually?
See example here:
https://github.com/tensorflow/tfx/blob/master/tfx/examples/chicago_taxi/trainer/model.py#L87

There shouldn't be an issue with the asset file path if using that, [we test for this](https://github.com/tensorflow/transform/commit/91ef1172dabba3558b9f52a37b8bb5b234befbda#diff-bfebe34154a0dfd9fc7b447fc9ed74e9).

Loading the transform saved model and using it looks like this:

> tf_transform_output = tft.TFTransformOutput(tf_transform_dir)
> transformed_features = tf_transform_output.transform_raw_features(raw_features)

**Comment by wsuchy** [comment] 2019-09-30 19:33
@zoyahav one of the reason is that TFT is expected to produce a hermetic TF Graph and we would like to use it as a standalone graph and eventually merge it manually with the actual model.
The problem I am pointing is in the way that the graph is serialized (with absolute paths in the protobuf file) and not in the loading.

**Comment by zoyahav** [comment] 2019-09-30 20:16
Thanks, I'm still not quite sure why you want to merge it manually with the model.
Using tf_transform_output.transform_raw_features(raw_features) in the model's input_fn will mean that when the model gets exported it will include the transform graph.

For legacy reasons we don't currently support loading the graph that way, this will likely change as we move forward with non-tf.compat.v1 TF 2.0 support, but I can't say when that will be.

Right now TFT graphs are serialized with the relative assets paths in the "saved_model_assets" collection even though it still has a Node referring to an absolute path, that should not be used.

**Comment by wsuchy** [comment] 2019-09-30 20:40
Thank you for clarifying.

**Comment by rmothukuru** [comment] 2019-10-01 05:26
@wsuchy ,
Can you please confirm if the issue is resolved so that we can close it. Thanks!

**Comment by wsuchy** [comment] 2019-10-01 17:02
@rmothukuru Based on @zoyahav comment :
> For legacy reasons we don't currently support loading the graph that way, this will likely change as we move forward with non-tf.compat.v1 TF 2.0 support, but I can't say when that will be. 

Some functionality is indeed missing yet I am able to get this working using `TFTransformOutput` component. I would rather set status to something between "legacy reasons" to "won't fix", but leave the decision to you.

**Comment by rmothukuru** [comment] 2019-10-03 03:01
Closing this issue as it has been answered by @zoyahav. Thanks!

**Closed by rmothukuru** 2019-10-03 03:01 UTC
Labels: stat:awaiting tensorflower, type:support
